databases:
  # 1. Managed PostgreSQL Database (Free plan, database expires in 90 days)
  - name: erpnext-db
    plan: free

services:
  # 2. Redis Cache & Queue Instance (type: keyvalue)
  - type: keyvalue
    name: erpnext-redis
    plan: free
    ipAllowList: [] # block public access, only allow internal traffic

  # 3. ERPNext App Web Service (unified container)
  - type: web
    name: erpnext-web
    repo: https://github.com/Aswinajay/erpnext
    env: docker
    dockerfilePath: Dockerfile
    dockerContext: .
    branch: version-16-hotfix
    plan: free # Free tier Web Service (spins down after 15 minutes of inactivity)
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: erpnext-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: erpnext-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: erpnext-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: erpnext-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: erpnext-db
          property: password
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: erpnext-redis
          property: connectionString
      - key: SITE_NAME
        value: site1.local
      - key: ADMIN_PASSWORD
        value: admin123 # You can change this to any secure password or generate it
      - key: ENCRYPTION_KEY
        generateValue: true
